### ISSUE TITLE
./exe/test fails with: Wrong type (expecting exact integer): es-error-cannot-convert-value

### ISSUE THREAD

**Issue by bentxt** [sph-mn/sescript#1]
hi
The test series fails with the error below. The same error is also raised for simple 'lambda' expressions

Backtrace:
In sph/lang/sescript/expressions.scm:
    109:2 19 (_ _)
In unknown file:
          18 (_ #<procedure 109be8f80 at ice-9/boot-9.scm:1037:28 ()> …)
In sph/tree.scm:
    396:2 17 (recurse-descend (define a (lambda (a b) 1 2 3)))
In sph/lang/sescript.scm:
    57:38 16 (_ _ #<procedure 109be8f60 at ice-9/boot-9.scm:1036:8 a…>)
In sph/lang/sescript/expressions.scm:
    145:2 15 (ses-define _ _)
In sph/list.scm:
    801:2 14 (loop _ _ _ ())
In sph/lang/sescript/expressions.scm:
    145:2 13 (_ _ (lambda (a b) 1 2 3))
In unknown file:
          12 (_ #<procedure 109be8e60 at ice-9/boot-9.scm:1037:28 ()> …)
In sph/tree.scm:
    396:2 11 (recurse-descend (lambda (a b) 1 2 3))
In sph/lang/sescript.scm:
    57:38 10 (_ _ #<procedure 109be8e40 at ice-9/boot-9.scm:1036:8 a…>)
In sph/lang/sescript/expressions.scm:
    188:2  9 (ses-lambda ((a b) 1 2 3) _)
In unknown file:
           8 (_ #<procedure 109be8de0 at ice-9/boot-9.scm:1037:28 ()> …)
In sph/tree.scm:
    396:2  7 (recurse-descend (begin 1 2 #<procedure 109eea7a0 at …>))
In sph/lang/sescript.scm:
    57:38  6 (_ _ #<procedure 109be8dc0 at ice-9/boot-9.scm:1036:8 a…>)
In sph/lang/sescript/expressions.scm:
    109:2  5 (ses-begin _ _)
In rnrs/base.scm:
   116:29  4 (map #<procedure 109be8da0 at sph/lang/sescript/expres…> …)
In sph/lang/sescript/expressions.scm:
    109:2  3 (_ _)
In unknown file:
           2 (_ #<procedure 109be8d00 at ice-9/boot-9.scm:1037:28 ()> …)
           1 (_ #<procedure 109be8ce0 at ice-9/boot-9.scm:1037:28 ()> …)
           0 (raise es-error-cannot-convert-value)

ERROR: In procedure raise:
Wrong type (expecting exact integer): es-error-cannot-convert-value

**Comment by jkalbhenn** [comment]
hi
thanks for the report. it should be fixed now. it was caused by a change in sph-lib.

**Comment by bentxt** [comment]
Ok, it works now thanks
