### ISSUE TITLE
improving portability

### ISSUE THREAD

**Issue by bentxt** [sph-mn/sescript#2]
hi
working on macos, there are two problems and possible solutions

- replace /usr/bin/guile with /usr/bin/env guile

- incompatible options in 'cp' in ./exe/install, this one I have no solution atm

**Comment by sph-mn** [comment]
#!/usr/bin/guile has now been changed to #!/usr/bin/env guile.
regarding the second point, it looks like macos cp does not support the long options, --recursive is -R and --remove-destination would be -f. --symbolic-link doesnt have an equivalent but it is not required.
the cp dependency could be replaced with scheme code. alternatively, the install script could be replaced by a simple shell script, which can check the cp variant used, which would be less work. im inclined to implement the latter on the next occasion.

**Comment by sph-mn** [comment]
converted the install script to use shell only.
